spring:
  profiles:
    active:
      - dev

---

server:
  port: 8201
spring:
  profiles: dev
  application:
    name: microservice-config-client
eureka:
  client:
    service-url:
      # 单机 defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/

---

spring:
  profiles: test
  application:
      name: microservice-config-guigu-tset



